apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservicio
  template:
    metadata:
      labels:
        app: microservicio
    spec:
      containers:
        - name: microservicio
          image: microservicio:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
